### ISSUE TITLE
XMLHttpRequest cannot load.The response had HTTP status code 403.

### ISSUE THREAD

**Issue by praducg** [chandrasekhar4u/node_wit_client#2]
XMLHttpRequest cannot load https://hu4xwdeme9.execute-api.us-east-1.amazonaws.com/DEV/bankingbot/accountsummary?userKey=1002. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8005' is therefore not allowed access. The response had HTTP status code 403.

**Comment by chandrasekhar4u** [comment]
Fixed by enabling cors at server side.

**Comment by praducg** [comment]
Hi Chandra,

Check whether you r getting the response from lambda service or not .Maybe
the internet is very slow in my home that's why not getting

Thanks
Pradeep
